package com.winter.charactersheet.enums;

public enum RaceEnum {
    AARAKOCRA("Aarakocra"),
    AASIMAR("Aasimar"),
    ANDROID("Android"),
    BUGBEAR("Bugbear"),
    CATFOLK("Catfolk"),
    CENTAUR("Centar"),
    CHANGELING("Changeling"),
    DHAMPIR("Dhampir"),
    DRAGONBORN("Dragonborn"),
    DROW("Drow"),
    DUERGAR("Duergar"),
    DWARF("Dwarf"),
    ELF("Elf"),
    FETCHLING("Fetchling"),
    FIRBOLG("Firbolg"),
    GENASI("Genasi"),
    GHORAN("Ghoran"),
    GILLMAN("Gillman"),
    GITH("Gith"),
    GNOME("Gnome"),
    GOBLIN("Goblin"),
    GOLIATH("Goliath"),
    GRIPPLI("Grippli"),
    GRUNG("Grung"),
    HALF_ELF("Half-elf"),
    HALFLING("Halfling"),
    HALF_ORC("Half-Orc"),
    HOBGOBLIN("Hobgoblin"),
    HUMAN("Human"),
    IFRIT("Ifrit"),
    KALASHTAR("Kalashtar"),
    KENKU("Kenku"),
    KITSUNE("Kitsune"),
    KOBOLD("Kobold"),
    LASHUNTA("Lashunta"),
    LEONIN("Leonin"),
    LIZARDFOLK("Lizardfolk"),
    LOCATHATH("Locathath"),
    LOXODON("Loxodon"),
    MERFOLK("Merfolk"),
    MINOTAUR("Minotaur"),
    MONKEY_GOBLIN("Monkey Goblin"),
    NAGAJI("Nagaji"),
    ORC("Orc"),
    ORC_OF_EBERRON("Orc of Eberron"),
    ORC_OF_EXANDRIA("Orc Of Exandria"),
    OREAD("Oread"),
    RATFOLK("Ratfolk"),
    SAMSARAN("Samsaran"),
    SATYR("Satyr"),
    SHIFTER("Shifter"),
    SIMIC_HYBRID("Simic Hybrid"),
    STRIX("Strix"),
    SULI("Suli"),
    SVIRFNEBLIN("Svirfneblin"),
    SYLPH("Sylph"),
    TABAXI("Tabaxi"),
    TENGU("Tengu"),
    TIEFLING("Tiefling"),
    TIEFLING_FERAL("Tiefling (Feral)"),
    TORTLE("Tortle"),
    TRITON("Triton"),
    UNDINE("Undine"),
    VANARA("Vanara"),
    VEDALKEN("Vedalken"),
    VERDAN("Verdan"),
    VISHKANYA("Vishkanya"),
    WARFORGED("Warforged"),
    WAYANG("Wayang"),
    WYVARAN("Wyvaran"),
    YUAN_TI_PUREBLOOD("Yuan-ti Pureblood");


    RaceEnum(String raceName){
        this.raceName = raceName;
    }
    private String raceName;

    public String getRaceName(){
        return raceName;
    }
}
